version: 2
updates:
- package-ecosystem: "composer"
  directory: "/"
  versioning-strategy: "increase"
  schedule:
    interval: "monthly"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
