on:
  - pull_request
  - push

name: CI

jobs:
  run:
    name: Tests

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
        psr-log-versions: [ '^1', '^2', '^3' ]
        exclude:
          - php-versions: '7.4'
            psr-log-versions: '^2'
          - php-versions: '7.4'
            psr-log-versions: '^3'

    runs-on: ${{ matrix.operating-system }}

    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install dependencies with composer
        run: composer install

      - name: Install PSR Log
        run: |
          composer require --with-all-dependencies psr/log:${{ matrix.psr-log-versions }}

      - name: Run tests
        run: make test
